name: docker-build-and-push

on:
  push:
    branches:
      - 'kubernete-helm'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker build -t drejsamurai/devops_project ./project_manager_backend
          docker push drejsamurai/devops_project          
  deploy:
        needs: build
        runs-on:
            - self-hosted
            - label-1
        steps:
            - uses: actions/checkout@v2
            
            - name: Run scripts
              run: |
                cd ../devops_project
                git pull origin kubernete-helm
                git checkout kubernete-helm
                cd k8s
                helm upgrade --install projectdb-chart projectdb-chart
                helm upgrade --install project-manager-backend-chart project-manager-backend-chart
                kubectl rollout restart deployment backenddeployment
